version: '3.8'

services:
  quicktext-pro:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - RATE_LIMIT_POINTS=50
      - RATE_LIMIT_DURATION=60
    restart: unless-stopped
    networks:
      - quicktext-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - quicktext-pro
    restart: unless-stopped
    networks:
      - quicktext-network

networks:
  quicktext-network:
    driver: bridge
